- hosts: rocky_servers
  become: true
  tasks:
    - name: Copy vulnerability scan script to remote servers
      copy:
        src: rocky_script.sh
        dest: /tmp/rocky_script.sh
        mode: '0755'

    - name: Run vulnerability scan script
      command: /tmp/rocky_script.sh
      register: scan_output

    - name: Save scan output to a log file on the remote server
      copy:
        content: "{{ scan_output.stdout }}"
        dest: /var/log/vulnerability_scan.log

    - name: Fetch scan output to local machine
      fetch:
        src: /var/log/vulnerability_scan.log
        dest: ./scan_results/{{ inventory_hostname }}_vulnerability_scan.log
        flat: yes

